version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-14.7
      - image: postgres:11.5
        environment:
          POSTGRES_USER: notary
          POSTGRES_DB: notary_test
          POSTGRES_PASSWORD: ""

    working_directory: /home/stackage/project

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: stack-notary-v2-{{ checksum "stack.yaml" }}-{{ checksum "notary.cabal" }}
      - restore_cache:
          key: stack-notary-v2-final-{{ checksum "stack.yaml" }}-{{ checksum "notary.cabal" }}
      - run: .circleci/setupenv.sh
      - run: stack build --only-dependencies
      - save_cache:
          key: stack-notary-v2-{{ checksum "stack.yaml" }}-{{ checksum "notary.cabal" }}
          paths:
            - ~/.stack
            - .stack-work
            - ~/.local
      - run: .circleci/build.sh
      - run: .circleci/test.sh
      - run: stack install --resolver=lts-14.7 hlint
      - save_cache:
          key: stack-notary-v2-final-{{ checksum "stack.yaml" }}-{{ checksum "notary.cabal" }}
          paths:
            - ~/.stack
            - .stack-work
            - ~/.local
      - run: .circleci/lint.sh
      - persist_to_workspace:
          root: ~/.local/bin/
          paths: notary
      - store_artifacts:
          path: ~/.local/bin/notary
          destination: notary

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
